package com.zmin.birthday.app.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zmin.birthday.mvp.model.entity.Birthday;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BIRTHDAY".
*/
public class BirthdayDao extends AbstractDao<Birthday, String> {

    public static final String TABLENAME = "BIRTHDAY";

    /**
     * Properties of entity Birthday.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Old_year = new Property(2, String.class, "old_year", false, "OLD_YEAR");
        public final static Property Old_month = new Property(3, String.class, "old_month", false, "OLD_MONTH");
        public final static Property Old_day = new Property(4, String.class, "old_day", false, "OLD_DAY");
        public final static Property Year = new Property(5, String.class, "year", false, "YEAR");
        public final static Property Month = new Property(6, String.class, "month", false, "MONTH");
        public final static Property Day = new Property(7, String.class, "day", false, "DAY");
    }


    public BirthdayDao(DaoConfig config) {
        super(config);
    }
    
    public BirthdayDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BIRTHDAY\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"OLD_YEAR\" TEXT," + // 2: old_year
                "\"OLD_MONTH\" TEXT," + // 3: old_month
                "\"OLD_DAY\" TEXT," + // 4: old_day
                "\"YEAR\" TEXT," + // 5: year
                "\"MONTH\" TEXT," + // 6: month
                "\"DAY\" TEXT);"); // 7: day
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BIRTHDAY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Birthday entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String old_year = entity.getOld_year();
        if (old_year != null) {
            stmt.bindString(3, old_year);
        }
 
        String old_month = entity.getOld_month();
        if (old_month != null) {
            stmt.bindString(4, old_month);
        }
 
        String old_day = entity.getOld_day();
        if (old_day != null) {
            stmt.bindString(5, old_day);
        }
 
        String year = entity.getYear();
        if (year != null) {
            stmt.bindString(6, year);
        }
 
        String month = entity.getMonth();
        if (month != null) {
            stmt.bindString(7, month);
        }
 
        String day = entity.getDay();
        if (day != null) {
            stmt.bindString(8, day);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Birthday entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String old_year = entity.getOld_year();
        if (old_year != null) {
            stmt.bindString(3, old_year);
        }
 
        String old_month = entity.getOld_month();
        if (old_month != null) {
            stmt.bindString(4, old_month);
        }
 
        String old_day = entity.getOld_day();
        if (old_day != null) {
            stmt.bindString(5, old_day);
        }
 
        String year = entity.getYear();
        if (year != null) {
            stmt.bindString(6, year);
        }
 
        String month = entity.getMonth();
        if (month != null) {
            stmt.bindString(7, month);
        }
 
        String day = entity.getDay();
        if (day != null) {
            stmt.bindString(8, day);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public Birthday readEntity(Cursor cursor, int offset) {
        Birthday entity = new Birthday( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // old_year
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // old_month
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // old_day
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // year
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // month
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // day
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Birthday entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOld_year(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOld_month(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOld_day(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setYear(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMonth(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDay(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Birthday entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Birthday entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Birthday entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
