package com.zmin.birthday.app.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zmin.birthday.mvp.model.entity.Birthday;

import com.zmin.birthday.app.db.dao.BirthdayDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig birthdayDaoConfig;

    private final BirthdayDao birthdayDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        birthdayDaoConfig = daoConfigMap.get(BirthdayDao.class).clone();
        birthdayDaoConfig.initIdentityScope(type);

        birthdayDao = new BirthdayDao(birthdayDaoConfig, this);

        registerDao(Birthday.class, birthdayDao);
    }
    
    public void clear() {
        birthdayDaoConfig.clearIdentityScope();
    }

    public BirthdayDao getBirthdayDao() {
        return birthdayDao;
    }

}
